version: 2.1
jobs:
 build:
    docker:
      - image: docker.io/golang:1.18-bullseye
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:

	  - checkout
	  - run: go run main.go
	  - setup_remote_docker:
          docker_layer_caching: true # ここでは、DLC はレイヤーを明示的にキャッシュし、リビルドを避けようとします
      - run: docker build .
