version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  
    steps:
      - checkout
      - run: go version

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKERHUB_USER/circleci-demo-docker:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/circleci-demo-docker:$TAG